<?php
/**
 * @version    4.7.6
 * @package    com_ra_mailman
 * @author     Charlie Bigley <webmaster@bigley.me.uk>
 * @copyright  2024 Charlie Bigley
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * 10/09/24 Generated by component-generator
 * 10/09/24 CB user ToolsHelper, not Ra_mailmanHelper
 * 12/09/24 CB use literals as headings
 * 12/10/24 CB Use literal for Save
 * 13/02/24 CB don't use getIdentity
 * 29/09/25 CB add field to select invitation list
 * 07/06/26 CB Add extra tab
 */
// No direct access
defined('_JEXEC') or die;

use \Joomla\CMS\HTML\HTMLHelper;
use \Joomla\CMS\Factory;
use \Joomla\CMS\Uri\Uri;
use \Joomla\CMS\Router\Route;
use \Joomla\CMS\Language\Text;
use \Ramblers\Component\Ra_tools\Site\Helpers\ToolsHelper;

$wa = $this->document->getWebAssetManager();
$wa->useScript('keepalive')
        ->useScript('form.validate');
HTMLHelper::_('bootstrap.tooltip');

// Load admin language file
$lang = Factory::getLanguage();
$lang->load('com_ra_mailman', JPATH_SITE);
$toolsHelper = new ToolsHelper;
?>

<div class="mailshot-edit front-end-edit">
    <?php if (!$this->canEdit) : ?>
        <h3>
            <?php throw new \Exception(Text::_('COM_RA_MAILMAN_ERROR_MESSAGE_NOT_AUTHORISED'), 403); ?>
        </h3>
    <?php else : ?>
        <?php if (!empty($this->item->id)): ?>
            <h2><?php echo 'Updating Mailshot'; ?>
            <?php else: ?>
                <h2><?php echo 'Creating Mailshot'; ?>
                <?php endif; ?>
                <?php echo ' for ' . $this->list_name; ?> </h2>
            <form id="form-mailshot"
                  action="<?php echo Route::_('index.php?option=com_ra_mailman&task=mailshotform.save'); ?>"
                  method="post" class="form-validate form-horizontal" enctype="multipart/form-data">
                      <?php
                      echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'event'));
                      echo HTMLHelper::_('uitab.addTab', 'myTab', 'event1', 'Basic');
                      ?>
                <input type="hidden" name="jform[id]" value="<?php echo isset($this->item->id) ? $this->item->id : ''; ?>" />

                <input type="hidden" name="jform[state]" value="<?php echo isset($this->item->state) ? $this->item->state : ''; ?>" />

                <?php echo $this->form->getInput('created_by'); ?>
                <?php echo $this->form->getInput('modified_by'); ?>
                <?php //echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'mailshot'));   ?>
                <?php //echo HTMLHelper::_('uitab.addTab', 'myTab', 'mailshot', Text::_('COM_RA_MAILMAN_TAB_MAILSHOT', true)); ?>

                <?php
                echo $this->form->renderField('title');
                echo $this->form->renderField('body');
//               if (!$this->date_sent == '0000-00-00') {
//                   echo $this->form->renderField('date_sent');
//               }
                echo $this->form->renderField('mail_list_id');

                echo HTMLHelper::_('uitab.endTab');
                echo HTMLHelper::_('uitab.addTab', 'myTab', 'event5', 'Extras');
                echo $this->form->renderField('attachment');
                if (ToolsHelper::isInstalled('com_ra_events')) {
                    $sql = 'SELECT COUNT(id) FROM `#__ra_events` ';
                    $sql .= 'WHERE bookable=1 AND DATEDIFF(event_date, CURRENT_DATE)>0 ';
                    $sql .= 'AND api_site_id IS NULL ';
                    $count = $toolsHelper->getValue($sql);
                    if ($count > 0) {
                        echo $this->form->renderField('event_id');
                    }
                }
                ?>
                <?php if (!empty($this->item->attachment)) : ?>
                    <?php $attachmentFiles = array_values(array_filter((array) $this->item->attachment)); ?>
                    <?php foreach ($attachmentFiles as $fileSingle) : ?>
                        <?php if (!is_array($fileSingle)) : ?>
                            <a href="<?php echo Route::_(Uri::root() . 'images/com_ra_mailman' . DIRECTORY_SEPARATOR . $fileSingle, false); ?>"><?php echo $fileSingle; ?></a> |
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <input type="hidden" name="jform[attachment_hidden]" id="jform_attachment_hidden" value="<?php echo implode(',', $attachmentFiles); ?>" />
                <?php endif; ?>
                <?php
                echo HTMLHelper::_('uitab.endTab');
                ?>
                <div class="control-group">
                    <div class="controls">

                        <?php if ($this->canSave): ?>
                            <button type="submit" class="validate btn btn-primary" name="save_quit">
                                <span class="fas fa-check" aria-hidden="true"></span>
                                <?php echo Text::_('Save & Close'); ?>
                            </button>
                            <button type="submit" class="validate btn btn-success" name="save_continue" onclick="this.form.task.value = 'mailshotform.savecontinue';">
                                <span class="fas fa-save" aria-hidden="true"></span>
                                <?php echo Text::_('Save & Send'); ?>
                            </button>
                            <button type="submit" class="validate btn btn-info" name="test_send" onclick="this.form.task.value = 'mailshotform.testsend';">
                                <span class="fas fa-envelope" aria-hidden="true"></span>
                                <?php echo Text::_('Send Test'); ?>
                            </button>
                        <?php endif; ?>
                        <a class="btn btn-danger"
                           href="<?php echo Route::_('index.php?option=com_ra_mailman&task=mailshotform.cancel'); ?>"
                           title="<?php echo Text::_('JCANCEL'); ?>">
                            <span class="fas fa-times" aria-hidden="true"></span>
                            <?php echo Text::_('JCANCEL'); ?>
                        </a>
                    </div>
                </div>

                <input type="hidden" name="option" value="com_ra_mailman"/>
                <input type="hidden" name="task" value="mailshotform.save"/>
                <?php echo HTMLHelper::_('form.token'); ?>
            </form>
        <?php endif; ?>
</div>
