<?php

/**
 * @version    4.1.8
 * @package    Com_Ra_mailman
 * @author     Charlie Bigley <webmaster@bigley.me.uk>
 * @copyright  2024 Charlie Bigley
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 * 10/09/24 Generated by component-generator
 * 10/09/24 CB redirect to mail_lsts on save and cancel
 * 12/10/24 CB Use literal for Save message
 * 30/03/26 CB/GPT-4.1 savecontinue added, pass list_id back to edit screen
 */

namespace Ramblers\Component\Ra_mailman\Site\Controller;

\defined('_JEXEC') or die;

use Joomla\CMS\Application\SiteApplication;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Multilanguage;
use Joomla\CMS\Language\Text;
use Joomla\CMS\MVC\Controller\FormController;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Utilities\ArrayHelper;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Ramblers\Component\Ra_mailman\Site\Helpers\Mailhelper;

/**
 * Mailshot class.
 *
 * @since  1.0.0
 */
class MailshotformController extends FormController {

    /**
     * Method to check out an item for editing and redirect to the edit form.
     *
     * @return  void
     *
     * @since   1.0.0
     *
     * @throws  Exception
     */
    public function edit($key = NULL, $urlVar = NULL) {
        // Get the previous edit id (if any) and the current edit id.
        $previousId = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
        $editId = $this->input->getInt('id', 0);

        // Set the user id for the user to edit in the session.
        $this->app->setUserState('com_ra_mailman.edit.mailshot.id', $editId);

        // Get the model.
        $model = $this->getModel('Mailshotform', 'Site');

        // Check out the item
        if ($editId) {
            $model->checkout($editId);
        }

        // Check in the previous user.
        if ($previousId) {
            $model->checkin($previousId);
        }

        // Redirect to the edit screen.
        $this->setRedirect(Route::_('index.php?option=com_ra_mailman&view=mailshotform&layout=edit', false));
    }

    /**
     * Method to save data.
     *
     * @return  void
     *
     * @throws  Exception
     * @since   1.0.0
     */
    public function save($key = NULL, $urlVar = NULL) {
        // Check for request forgeries.
        $this->checkToken();

        // Initialise variables.
        $model = $this->getModel('Mailshotform', 'Site');

        // Get the user data.
        $data = $this->input->get('jform', array(), 'array');

        // Validate the posted data.
        $form = $model->getForm();

        if (!$form) {
            throw new \Exception($model->getError(), 500);
        }

        // Send an object which can be modified through the plugin event
        $objData = (object) $data;
        $this->app->triggerEvent(
                'onContentNormaliseRequestData',
                array($this->option . '.' . $this->context, $objData, $form)
        );

        $data = (array) $objData;

        // Validate the posted data.
        $data = $model->validate($form, $data);
        $list_id = $data['mail_list_id'];

        // Check for errors.
        if ($data === false) {
            // Get the validation messages.
            $errors = $model->getErrors();

            // Push up to three validation messages out to the user.
            for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++) {
                if ($errors[$i] instanceof \Exception) {
                    $this->app->enqueueMessage($errors[$i]->getMessage(), 'warning');
                } else {
                    $this->app->enqueueMessage($errors[$i], 'warning');
                }
            }

            $jform = $this->input->get('jform', array(), 'ARRAY');

            // Save the data in the session.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $jform);

            // Redirect back to the edit screen.
            $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
            $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
            $target .= '&list_id=' . $list_id;  
            $this->setRedirect(Route::_($target, false));

            $this->redirect();
        }

        // Attempt to save the data.
        $return = $model->save($data);

        // Check for errors.
        if ($return === false) {
            // Save the data in the session.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $data);

            // Redirect back to the edit screen.
            $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
            $this->setMessage(Text::sprintf('Save failed', $model->getError()), 'warning');
            $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
            $target .= '&list_id=' . $list_id;
            $this->setRedirect(Route::_($target, false));
            $this->redirect();
        }

        // Check in the profile.
        if ($return) {
            $model->checkin($return);
        }

        // Clear the profile id from the session.
        $this->app->setUserState('com_ra_mailman.edit.mailshot.id', null);

        // Redirect to the list screen.
        if (!empty($return)) {
            $this->setMessage(Text::_('Mailshot saved successfully'));
        }

        $menu = Factory::getApplication()->getMenu();
        $item = $menu->getActive();
        $url = (empty($item->link) ? 'index.php?option=com_ra_mailman&view=mail_lsts' : $item->link);
        $this->setRedirect(Route::_($url, false));

        // Flush the data from the session.
        $this->app->setUserState('com_ra_mailman.edit.mailshot.data', null);

        // Invoke the postSave method to allow for the child class to access the model.
        $this->postSaveHook($model, $data);
    }

         /**
         * Custom save and continue editing action.
         *
         * Saves the data and redisplays the edit form for continued editing.
         */
        public function savecontinue($key = NULL, $urlVar = NULL) {
            // Check for request forgeries.
            $this->checkToken();

            // Initialise variables.
            $model = $this->getModel('Mailshotform', 'Site');

            // Get the user data.
            $data = $this->input->get('jform', array(), 'array');
            $list_id = $data['mail_list_id'];

            // Validate the posted data.
            $form = $model->getForm();
            if (!$form) {
                throw new \Exception($model->getError(), 500);
            }

            // Send an object which can be modified through the plugin event
            $objData = (object) $data;
            $this->app->triggerEvent(
                'onContentNormaliseRequestData',
                array($this->option . '.' . $this->context, $objData, $form)
            );
            $data = (array) $objData;

            // Validate the posted data.
            $data = $model->validate($form, $data);

            // Check for errors.
            if ($data === false) {
                // Get the validation messages.
                $errors = $model->getErrors();
                for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++) {
                    if ($errors[$i] instanceof \Exception) {
                        $this->app->enqueueMessage($errors[$i]->getMessage(), 'warning');
                    } else {
                        $this->app->enqueueMessage($errors[$i], 'warning');
                    }
                }
                $jform = $this->input->get('jform', array(), 'ARRAY');
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $jform);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;      
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            // Attempt to save the data.
            $return = $model->save($data);

            // Check for errors.
            if ($return === false) {
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $data);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $this->setMessage(Text::sprintf('Save failed', $model->getError()), 'warning');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            // Check in the profile.
            if ($return) {
                $model->checkin($return);
            }

            // Keep the profile id in the session for continued editing.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.id', $return);

            // Set success message and redirect back to the edit form.
            $this->setMessage(Text::_('Mailshot saved successfully'));
            $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $return;
            $target .= '&list_id=' . $list_id;
            $this->setRedirect(Route::_($target, false));

            // Flush the data from the session.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', null);

            // Invoke the postSave method to allow for the child class to access the model.
            $this->postSaveHook($model, $data);
        }

        /**
         * Save the current mailshot, send a draft/test email, and return to the edit screen.
         */
        public function testsend($key = NULL, $urlVar = NULL) {
            // Check for request forgeries.
            $this->checkToken();

            $model = $this->getModel('Mailshotform', 'Site');
            $data = $this->input->get('jform', array(), 'array');
            $list_id = $data['mail_list_id'] ?? 0;

            $form = $model->getForm();
            if (!$form) {
                throw new \Exception($model->getError(), 500);
            }

            $objData = (object) $data;
            $this->app->triggerEvent(
                'onContentNormaliseRequestData',
                array($this->option . '.' . $this->context, $objData, $form)
            );
            $data = (array) $objData;
            $data = $model->validate($form, $data);

            if ($data === false) {
                $errors = $model->getErrors();
                for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++) {
                    if ($errors[$i] instanceof \Exception) {
                        $this->app->enqueueMessage($errors[$i]->getMessage(), 'warning');
                    } else {
                        $this->app->enqueueMessage($errors[$i], 'warning');
                    }
                }

                $jform = $this->input->get('jform', array(), 'ARRAY');
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $jform);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            $return = $model->save($data);

            if ($return === false) {
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $data);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $this->setMessage(Text::sprintf('Save failed', $model->getError()), 'warning');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            if ($return) {
                $model->checkin($return);
            }

            $mailHelper = new Mailhelper;
            if ($mailHelper->sendDraft((int) $return)) {
                $this->setMessage($mailHelper->message, 'message');
            } else {
                $this->setMessage($mailHelper->message ?: 'Unable to send test email', 'warning');
            }

            $this->app->setUserState('com_ra_mailman.edit.mailshot.id', $return);
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', null);

            $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $return;
            $target .= '&list_id=' . $list_id;
            $this->setRedirect(Route::_($target, false));

            $this->postSaveHook($model, $data);
        }

        /**
         * Save the current mailshot, send it, and return to the mailing-list screen.
         */
        public function saveandsend($key = NULL, $urlVar = NULL) {
            // Check for request forgeries.
            $this->checkToken();

            $model = $this->getModel('Mailshotform', 'Site');
            $data = $this->input->get('jform', array(), 'array');
            $list_id = $data['mail_list_id'] ?? 0;

            $form = $model->getForm();
            if (!$form) {
                throw new \Exception($model->getError(), 500);
            }

            $objData = (object) $data;
            $this->app->triggerEvent(
                'onContentNormaliseRequestData',
                array($this->option . '.' . $this->context, $objData, $form)
            );
            $data = (array) $objData;
            $data = $model->validate($form, $data);

            if ($data === false) {
                $errors = $model->getErrors();
                for ($i = 0, $n = count($errors); $i < $n && $i < 3; $i++) {
                    if ($errors[$i] instanceof \Exception) {
                        $this->app->enqueueMessage($errors[$i]->getMessage(), 'warning');
                    } else {
                        $this->app->enqueueMessage($errors[$i], 'warning');
                    }
                }

                $jform = $this->input->get('jform', array(), 'ARRAY');
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $jform);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            $return = $model->save($data);

            if ($return === false) {
                $this->app->setUserState('com_ra_mailman.edit.mailshot.data', $data);
                $id = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');
                $this->setMessage(Text::sprintf('Save failed', $model->getError()), 'warning');
                $target = 'index.php?option=com_ra_mailman&view=mailshotform&layout=edit&id=' . $id;
                $target .= '&list_id=' . $list_id;
                $this->setRedirect(Route::_($target, false));
                $this->redirect();
            }

            if ($return) {
                $model->checkin($return);
            }

            $mailHelper = new Mailhelper;
            $total = (int) $mailHelper->countSubscribers((int) $list_id);
            $mailHelper->send((int) $return, $total);

            if (empty($mailHelper->messages)) {
                $this->setMessage(Text::_('Mailshot send started'));
            }

            $this->app->setUserState('com_ra_mailman.edit.mailshot.id', null);
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', null);

            $menu = Factory::getApplication()->getMenu();
            $item = $menu->getActive();
            $url = (empty($item->link) ? 'index.php?option=com_ra_mailman&view=mail_lsts' : $item->link);
            $this->setRedirect(Route::_($url, false));

            $this->postSaveHook($model, $data);
        }
    /**
     * Method to abort current operation
     *
     * @return void
     *
     * @throws Exception
     */
    public function cancel($key = NULL) {

        // Get the current edit id.
        $editId = (int) $this->app->getUserState('com_ra_mailman.edit.mailshot.id');

        // Get the model.
        $model = $this->getModel('Mailshotform', 'Site');

        // Check in the item
        if ($editId) {
            $model->checkin($editId);
        }

        $menu = Factory::getApplication()->getMenu();
        $item = $menu->getActive();
        $url = (empty($item->link) ? 'index.php?option=com_ra_mailman&view=mail_lsts' : $item->link);
        $this->setRedirect(Route::_($url, false));
    }

    /**
     * Method to remove data
     *
     * @return  void
     *
     * @throws  Exception
     *
     * @since   1.0.0
     */
    public function remove() {
        $model = $this->getModel('Mailshotform', 'Site');
        $pk = $this->input->getInt('id');

        // Attempt to save the data
        try {
            // Check in before delete
            $return = $model->checkin($return);
            // Clear id from the session.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.id', null);

            $menu = $this->app->getMenu();
            $item = $menu->getActive();
            $url = (empty($item->link) ? 'index.php?option=com_ra_mailman&view=mailshots' : $item->link);

            if ($return) {
                $model->delete($pk);
                $this->setMessage(Text::_('COM_RA_MAILMAN_ITEM_DELETED_SUCCESSFULLY'));
            } else {
                $this->setMessage(Text::_('COM_RA_MAILMAN_ITEM_DELETED_UNSUCCESSFULLY'), 'warning');
            }


            $this->setRedirect(Route::_($url, false));
            // Flush the data from the session.
            $this->app->setUserState('com_ra_mailman.edit.mailshot.data', null);
        } catch (\Exception $e) {
            $errorType = ($e->getCode() == '404') ? 'error' : 'warning';
            $this->setMessage($e->getMessage(), $errorType);
            $this->setRedirect('index.php?option=com_ra_mailman&view=mailshots');
        }
    }

    /**
     * Function that allows child controller access to model data
     * after the data has been saved.
     *
     * @param   BaseDatabaseModel  $model      The data model object.
     * @param   array              $validData  The validated data.
     *
     * @return  void
     *
     * @since   1.6
     */
    protected function postSaveHook(BaseDatabaseModel $model, $validData = array()) {

    }

}
